CREATE TABLE PARAMS (
PKEY CHAR(15) UNIQUE NOT NULL,
PVALUE CHAR(50) );

CREATE TABLE ROLES (
ID_ROLE INTEGER NOT NULL,
NAME_ROLE CHAR(30) NOT NULL,
PRIMARY KEY (ID_ROLE));

CREATE TABLE ACTIONS (
ID_ACTION INTEGER NOT NULL,
NAME_ACTION CHAR(30) NOT NULL,
PRIMARY KEY (ID_ACTION));

CREATE TABLE USERS (
ID_USER INTEGER NOT NULL,
PERSON_ID INTEGER,
ROLE_ID INTEGER NOT NULL,
LOGIN CHAR(20) UNIQUE NOT NULL,
PASSWORD CHAR(30) NOT NULL,
PRIMARY KEY (ID_USER),
CONSTRAINT FK_USERS_ROLES FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID_ROLE) ON DELETE RESTRICT ON UPDATE CASCADE);

CREATE TABLE ROLE_ACTION (
ROLE_ID INTEGER NOT NULL,
ACTION_ID INTEGER NOT NULL,
PRIMARY KEY (ROLE_ID, ACTION_ID),
CONSTRAINT FK_ROL_ACT_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID_ROLE) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT FK_ROL_ACT_ACTION FOREIGN KEY (ACTION_ID) REFERENCES ACTIONS(ID_ACTION) ON DELETE CASCADE ON UPDATE CASCADE);